### ISSUE TITLE
Child selector styles not being applied

### ISSUE THREAD

**Issue by caseyjhol** [FelixSchwarz/mjml-python#44]
```css
.parent {
  overflow: hidden;
  box-shadow: 0 4px 10px 0px rgba(0, 0, 0, 0.1);
}
.parent > table > tbody > tr > td,
.parent > table > tbody > tr > td > div {
  border-radius: 3px;
}
```

```html
<div class="parent">
    <table>
        <tbody>
            <tr>
                <td>
                    <div>
                        Test
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>
```

Actual:
```html
<div class="parent" style="overflow: hidden; box-shadow: 0 4px 10px 0px rgba(0, 0, 0, 0.1);">
    <table>
        <tbody>
            <tr>
                <td>
                    <div>
                        Test
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>
```

Expected:
```html
<div class="parent" style="overflow: hidden; box-shadow: 0 4px 10px 0px rgba(0, 0, 0, 0.1);">
    <table>
        <tbody>
            <tr>
                <td style="border-radius: 3px;">
                    <div style="border-radius: 3px;">
                        Test
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>
```

Originally I thought this was an [issue with css-inline](https://github.com/Stranger6667/css-inline/issues/185), but it's actually an issue on our end. BeautifulSoup is escaping the carets (`>` becomes `&gt;`), preventing child selectors from getting applied. We can either use `html.unescape` in mjStyle, or perhaps we can decode from BeautifulSoup using `formatter=None`. It might be better to limit this to mjStyle only and use `html.unescape` so as not to affect the rest of the HTML. I'm still investigating the best approach.
